env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - AWS_ACCESS_KEY_ID=local
    - AWS_SECRET_ACCESS_KEY=secret
    - BOTO_CONFIG=/dev/null

dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements_build.txt

script:
  - py.test -v

after_success:
  - codecov
